# -*- coding: utf-8 -*-
"""Project: Demand forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOoiHeQhytJQZ9W8AYUDYu-Hr1ovnA6T

<details>
"""

import pandas as pd
#from utils import printm, print_info

# ----------------
# Loading dataset
# ----------------
csv_path = 'demand_forecasting.csv'

try:
    df = pd.read_csv(csv_path)
    print("CSV loaded successfully!")
except FileNotFoundError:
    print(f"Error: The file at {csv_path} was not found. Please update the path.")

# import importlib
# import eda_pipeline
# importlib.reload(eda_pipeline)
# from eda_pipeline import EDAPipeline

# # Initialize and execute the modular EDA pipeline
# eda_pipe = EDAPipeline()
# eda_pipe.run(df)

print(f'\nDataset Shape:\n{df.shape[0]} rows, {df.shape[1]} columns')
print(f'\n----------------------------------')
print(f'\nDataset info:\n')
print(f'{df.info()}')
print(f'\n----------------------------------')
print(f'\nDataset description:\n')
print(f'{df.describe()}')
print(f'\n----------------------------------')
print(f'\nMissing values count:\n{df.isnull().sum()}')
print(f'\n----------------------------------')
print(f'\nDuplicate rows: {df.duplicated().sum()}')
print(f'\n----------------------------------')
print(f'\nUnique values count:\n{df.nunique()}')
print(f'\n----------------------------------')
print(f'\nDataset head:\n{df.head()}')
print(f'\n----------------------------------')
print(f'\nDataset tail:\n{df.tail()}')
print(f'\n----------------------------------')

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


# A. Temporal & Cyclical Features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfWeek'] = df['Date'].dt.dayofweek
df['WeekOfYear'] = df['Date'].dt.isocalendar().week.astype(int)
# ------------------------------------------------------------

# Cyclical Encoding (Fixed missing '*' and markdown bullets)
df['Month_Sin'] = np.sin(2 * np.pi * df['Month'] / 12)
df['Month_Cos'] = np.cos(2 * np.pi * df['Month'] / 12)
df['DayOfWeek_Sin'] = np.sin(2 * np.pi * df['DayOfWeek'] / 7)
df['DayOfWeek_Cos'] = np.cos(2 * np.pi * df['DayOfWeek'] / 7)
# ------------------------------------------------------------

# B. Fourier Terms for Multi-Year Seasonality (Fixed missing subtraction '-')
t = (df['Date'] - df['Date'].min()).dt.days
df['Fourier_Sin_1'] = np.sin(2 * np.pi * t / 365.25)
df['Fourier_Cos_1'] = np.cos(2 * np.pi * t / 365.25)
# ------------------------------------------------------------

# C. Grouped Lag & Rolling Window Features (Per Store & Product)
grouped = df.groupby(['Store ID', 'Product ID'])
# ------------------------------------------------------------

# Lag Features (Past Demand)
df['Demand_Lag_7'] = grouped['Demand'].shift(7)
df['Demand_Lag_30'] = grouped['Demand'].shift(30)
df['Demand_Lag_365'] = grouped['Demand'].shift(365)  # Multi-year YoY lag
# ------------------------------------------------------------

# Rolling Window Statistics
df['Demand_Rolling_Mean_7'] = grouped['Demand'].shift(1).rolling(window=7, min_periods=1).mean()
df['Demand_Rolling_Std_7'] = grouped['Demand'].shift(1).rolling(window=7, min_periods=1).std()
# ------------------------------------------------------------

# D. Competitive Pricing Shift Features (Fixed missing subtraction '-')
df['Price_Diff'] = df['Price'] - df['Competitor Pricing']
df['Price_Ratio'] = df['Price'] / (df['Competitor Pricing'] + 1e-5)
# ------------------------------------------------------------

# Handle NaN values generated from shifts/rolling windows
df = df.bfill().fillna(0)
# ------------------------------------------------------------

# One-Hot Encoding for nominal features
nominal_cols = ['Category', 'Region', 'Weather Condition', 'Seasonality']
df = pd.get_dummies(df, columns=nominal_cols, drop_first=True)
# ------------------------------------------------------------


# Scale numerical continuous variables
scale_cols = ['Inventory Level', 'Units Sold', 'Units Ordered', 'Price', 'Discount', 'Competitor Pricing', 'Price_Diff', 'Price_Ratio']
scaler = StandardScaler()
df[scale_cols] = scaler.fit_transform(df[scale_cols])
# ------------------------------------------------------------

# Strict time-based split to prevent data leakage
split_date = '2024-01-01'
train_df = df[df['Date'] < split_date]
test_df = df[df['Date'] >= split_date]

processed_data = df
train_data = train_df
test_data = test_df

print(f'Training Set Shape: {train_df.shape}')
print(f'Testing Set Shape: {test_df.shape}')
# ------------------------------------------------------------

import importlib
import preprocessing
importlib.reload(preprocessing)
from preprocessing import DataPreprocessingPipeline

# *****************************
# RUN PREPROCESSING PIPELINE
# *****************************
pipeline = DataPreprocessingPipeline()
df = pipeline.fit_transform(df)